#!/bin/sh

ESLINT_NAMES='\.(es6|jsx|js)$'
PRETTIER_NAMES='\.(es6|jsx|js|scss|json)$'

ESLINT_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E $ESLINT_NAMES)
PRETTIER_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E $PRETTIER_NAMES)

if [[ ! -z $ESLINT_FILES ]]
then
  echo "===Running Eslint==="
  echo $ESLINT_FILES | xargs ./node_modules/.bin/eslint --fix || exit 1
  echo $ESLINT_FILES | xargs git add
fi

if [[ ! -z $PRETTIER_FILES ]]
then
  echo "===Running Prettier==="
  echo $PRETTIER_FILES | xargs ./node_modules/.bin/prettier --write || exit 1
  echo $PRETTIER_FILES | xargs git add
fi

echo "===Linting passed==="